.\" Manpage for Directory diSplay.
.\" by ElCapitan, https://github.com/at-elcapitan

.TH "ds" 1 "27 Feb 2026" "GNU" "Directory diSplay"
.SH NAME
Directory diSplay (DS) - display current directory

.SH SYNOPSIS
ds [OPTION] [DIRECTORY]

.SH DESCRIPTION
ds is a simple directory tree display application, created to make it easier to get information about a folder.

.SH OPTIONS
.TP
\fB \-\-all\fR, \fB\-a\fR 
display all directory context

.TP
\fB --full-size\fR, \fB-f\fR
disable file name shortening

.TP
\fB --size\fR, \fB-s\fR
display files size

.TP
\fB --access\fR, \fB-A\fR
display access options

.TP
\fB --version\fR
display current program version

.TP
\fB --help\fR
display this man page



